# description: Where to export to
# type: string
# required: true
dest: notion

# description: should body be included
# type: boolean
# includeBody: true

# description: should stubs be included
# type: boolean
# includeStubs: TODO

# description: undefined
# type: array
# ignore: TODO

# description: include or exclude certain vaults
# type: object
# vaults: TODO

# description: Api key for Notion
# type: string
# required: true
apiKey: secret_vZeKOgxnUYH4WM0kNYtEIJZazgtC3vP0yFZA4qiu8Me

# description: vault to export from
# type: string
# required: true
vault: Personal